"use client";

/**
 * MiniChallengeWidget — inline MCQ for student practice.
 * Generated by the mentor agent on-the-fly — not persisted to DB.
 */
import { useState } from"react";
import { cn } from"@/lib/utils";
import { Check, X } from"lucide-react";

interface MCQOption {
 text: string;
 is_correct: boolean;
 explanation?: string;
}

interface MiniChallengeWidgetProps {
 props: {
 question: string;
 options: MCQOption[];
 concept?: string;
 };
}

export function MiniChallengeWidget({ props }: MiniChallengeWidgetProps) {
 const { question, options, concept } = props;
 const [selected, setSelected] = useState<number | null>(null);
 const [revealed, setRevealed] = useState(false);

 if (!options || options.length === 0) return null;

 function handleSelect(index: number) {
 if (revealed) return;
 setSelected(index);
 setRevealed(true);
 }

 const isCorrect = selected !== null && options[selected]?.is_correct;

 return (
 <div className="space-y-3">
 <div className="text-xs font-semibold text-accent-primary dark:text-accent-secondary uppercase tracking-wider">
 Mini Challenge {concept && `— ${concept}`}
 </div>

 <div className="p-4 rounded-xl bg-bg-card border border-border-subtle">
 <p className="text-sm font-medium text-text-subheading mb-3">
 {question}
 </p>

 <div className="space-y-2">
 {options.map((opt, i) => {
 const isSelected = selected === i;
 const showCorrect = revealed && opt.is_correct;
 const showWrong = revealed && isSelected && !opt.is_correct;

 return (
 <button
 key={i}
 onClick={() => handleSelect(i)}
 disabled={revealed}
 className={cn(
"w-full text-left flex items-center gap-3 px-4 py-3 rounded-xl text-sm",
"border transition-all duration-200",
 !revealed
 ?"border-border-subtle hover:border-blue-400 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-bg-hover active:scale-[0.98]"
 : showCorrect
 ?"border-green-300 dark:border-green-800 bg-green-50 dark:bg-green-950/20"
 : showWrong
 ?"border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-950/20"
 :"border-border-subtle opacity-50",
"disabled:cursor-default",
 )}
 >
 <span
 className={cn(
"w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0",
 showCorrect
 ?"bg-green-500 text-white"
 : showWrong
 ?"bg-red-500 text-white"
 :"bg-bg-section text-text-muted",
 )}
 >
 {showCorrect ? (
 <Check className="w-3 h-3" />
 ) : showWrong ? (
 <X className="w-3 h-3" />
 ) : (
 String.fromCharCode(65 + i)
 )}
 </span>
 <span
 className={cn(
 showCorrect
 ?"text-green-800 dark:text-green-300"
 : showWrong
 ?"text-red-800 dark:text-red-300"
 :"text-text-body",
 )}
 >
 {opt.text}
 </span>
 </button>
 );
 })}
 </div>

 {/* Result feedback */}
 {revealed && (
 <div
 className={cn(
"mt-3 p-3 rounded-lg text-sm",
 isCorrect
 ?"bg-green-50 dark:bg-green-950/20 text-green-700 dark:text-green-400"
 :"bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400",
 )}
 >
 {isCorrect ?"Chính xác! 🎉" :"Chưa đúng."}
 {selected !== null && options[selected]?.explanation && (
 <p className="mt-1 text-text-muted text-xs">
 {options[selected].explanation}
 </p>
 )}
 </div>
 )}
 </div>
 </div>
 );
}
